# Generated by Django 2.1.2 on 2019-01-31 23:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20181004_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 1, 31, 23, 56, 29, 929779, tzinfo=utc), null=True),
        ),
    ]
