# Generated by Django 2.0.6 on 2019-02-17 01:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('keyword', '0001_initial'),
        ('blog', '0002_auto_20181004_2011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='keywords',
        ),
        migrations.AddField(
            model_name='post',
            name='keywords',
            field=models.ManyToManyField(blank=True, to='keyword.Keyword'),
        ),
        migrations.AlterField(
            model_name='post',
            name='publish_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 2, 17, 1, 23, 41, 703235, tzinfo=utc), null=True),
        ),
    ]
