# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-26 22:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_upvotes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-hot_score', '-publish_date', '-modified']},
        ),
        migrations.AddField(
            model_name='post',
            name='hot_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
