# Generated by Django 2.0.6 on 2019-02-18 14:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190216_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 2, 18, 14, 55, 44, 254243, tzinfo=utc), null=True),
        ),
    ]
