# Generated by Django 2.1.2 on 2019-02-18 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190218_0955'),
        ('blog', '0004_auto_20190205_0139'),
    ]

    operations = [
    ]
