# Generated by Django 2.1.2 on 2019-02-25 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_merge_20190218_1507'),
        ('blog', '0006_auto_20190223_1832'),
    ]

    operations = [
    ]
