# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-01-28 06:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20170926_2216'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-vote_score', 'num_vote_up', '-publish_date', '-modified']},
        ),
    ]
