# Generated by Django 2.0.6 on 2019-02-28 22:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20190226_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 2, 28, 22, 40, 26, 237977, tzinfo=utc), null=True),
        ),
    ]
