# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-01-28 06:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20180128_0134'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-vote_score', '-num_vote_up', '-publish_date', '-modified']},
        ),
    ]
