# Generated by Django 2.1.7 on 2019-03-31 17:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20190331_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 31, 17, 49, 49, 369138, tzinfo=utc), null=True),
        ),
    ]
