# Generated by Django 2.1.7 on 2019-03-31 17:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20190331_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 31, 17, 52, 10, 223830, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(max_length=205, unique=True),
        ),
    ]
