# Generated by Django 2.1.7 on 2019-04-14 18:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20190331_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 4, 14, 18, 55, 49, 269363, tzinfo=utc), null=True),
        ),
    ]
