# Generated by Django 2.0.6 on 2018-08-17 01:36

import apps.pages.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=200)),
                ('header_image', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=apps.pages.models.upload_location, width_field='width_field')),
                ('width_field', models.IntegerField(default=0)),
                ('height_field', models.IntegerField(default=0)),
                ('draft', models.BooleanField(default=False)),
                ('body', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
