# Generated by Django 2.0.6 on 2018-08-17 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='draft',
        ),
        migrations.AddField(
            model_name='page',
            name='show_title',
            field=models.BooleanField(default=True),
        ),
    ]
