# Generated by Django 2.1.2 on 2018-10-10 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20180816_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='height_field',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='width_field',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
