# Generated by Django 2.0.6 on 2018-11-13 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20181010_0340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='description',
            new_name='body',
        ),
    ]
