# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-17 02:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20170815_2254'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectpost',
            options={'ordering': ['post_order']},
        ),
        migrations.RenameField(
            model_name='projectpost',
            old_name='page_order',
            new_name='post_order',
        ),
    ]
