# Generated by Django 2.0.6 on 2019-02-17 01:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20181113_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='publish_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 2, 17, 1, 23, 41, 715203, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='projectpost',
            name='publish_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 2, 17, 1, 23, 41, 714206, tzinfo=utc), null=True),
        ),
    ]
