# Generated by Django 2.0.6 on 2019-02-18 14:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('keyword', '0001_initial'),
        ('project', '0005_auto_20190216_2027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='keywords',
        ),
        migrations.AddField(
            model_name='project',
            name='keywords',
            field=models.ManyToManyField(blank=True, to='keyword.Keyword'),
        ),
        migrations.AlterField(
            model_name='project',
            name='publish_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 2, 18, 14, 55, 44, 266211, tzinfo=utc), null=True),
        ),
        migrations.RemoveField(
            model_name='projectpost',
            name='keywords',
        ),
        migrations.AddField(
            model_name='projectpost',
            name='keywords',
            field=models.ManyToManyField(blank=True, to='keyword.Keyword'),
        ),
        migrations.AlterField(
            model_name='projectpost',
            name='publish_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 2, 18, 14, 55, 44, 265214, tzinfo=utc), null=True),
        ),
    ]
