# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-17 03:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_auto_20170816_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpost',
            name='post_order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
