# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-20 02:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_auto_20170816_2303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectpost',
            name='parent',
        ),
    ]
