# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-23 23:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_remove_projectpost_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='pages',
            field=models.ManyToManyField(blank=True, null=True, to='project.ProjectPost'),
        ),
    ]
