# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-24 04:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_auto_20170823_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='upvotes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectpost',
            name='upvotes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
