# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-26 22:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_auto_20170826_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpost',
            name='hot_score',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='projectpost',
            name='keywords',
            field=models.TextField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='projectpost',
            name='upvotes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
