# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-26 22:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_auto_20170826_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpost',
            name='keywords',
            field=models.TextField(blank=True, null=True),
        ),
    ]
