# Generated by Django 2.1.7 on 2019-03-31 17:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_auto_20190331_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='publish_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 31, 17, 49, 49, 380108, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(max_length=205, unique=True),
        ),
        migrations.AlterField(
            model_name='projectpost',
            name='publish_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 31, 17, 49, 49, 379106, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='projectpost',
            name='slug',
            field=models.SlugField(max_length=205, unique=True),
        ),
    ]
