# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-27 02:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_auto_20170826_1825'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-vote_score', '-publish_date', '-modified']},
        ),
        migrations.AlterModelOptions(
            name='projectpost',
            options={'ordering': ['-post_order', '-publish_date', '-modified']},
        ),
        migrations.RemoveField(
            model_name='project',
            name='upvotes',
        ),
        migrations.RemoveField(
            model_name='projectpost',
            name='hot_score',
        ),
        migrations.RemoveField(
            model_name='projectpost',
            name='upvotes',
        ),
        migrations.AddField(
            model_name='project',
            name='num_vote_down',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='num_vote_up',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='vote_score',
            field=models.FloatField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='projectpost',
            name='num_vote_down',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='projectpost',
            name='num_vote_up',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='projectpost',
            name='vote_score',
            field=models.FloatField(db_index=True, default=0),
        ),
    ]
