# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-27 02:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0013_auto_20170926_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='pages',
            field=models.ManyToManyField(blank=True, to='project.ProjectPost'),
        ),
    ]
