# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-11-02 02:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0014_auto_20170926_2219'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectpost',
            options={'ordering': ['post_order', '-publish_date', '-modified']},
        ),
        migrations.AddField(
            model_name='project',
            name='authors',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
