# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-01-28 06:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0016_auto_20171101_2212'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-vote_score', '-num_vote_up', '-publish_date', '-modified']},
        ),
        migrations.AlterModelOptions(
            name='projectpost',
            options={'ordering': ['post_order', '-num_vote_up', '-publish_date', '-modified']},
        ),
    ]
