# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-26 22:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_auto_20170824_0021'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-confidence', '-timestamp']},
        ),
        migrations.AddField(
            model_name='comment',
            name='confidence',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
