# Generated by Django 2.0.6 on 2018-08-10 12:25

import apps.geba_auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geba_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to=apps.geba_auth.models.upload_location, width_field='width_field'),
        ),
        migrations.AddField(
            model_name='user',
            name='height_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='width_field',
            field=models.IntegerField(default=0),
        ),
    ]
