# Generated by Django 2.0.6 on 2018-09-04 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geba_auth', '0002_auto_20180810_0825'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
